In [1]:
from IPython.core.display import display, HTML
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import warnings
import helper_functions as hf

warnings.filterwarnings('ignore')

In [2]:
installs = pd.read_csv('installments_payments.csv').sort_values(
    ['SK_ID_PREV','NUM_INSTALMENT_NUMBER'])
installs['PAY_DIFF'] = installs['AMT_INSTALMENT'] - installs['AMT_PAYMENT']
installs['DAYS_DIFF'] = installs['DAYS_INSTALMENT'] - installs['DAYS_ENTRY_PAYMENT']
installs['PAY_DIFF2'] = [1 if i >= 0 else 0 for i in installs['PAY_DIFF']]
installs['DAYS_DIFF2'] = [1 if i >= 0 else 0 for i in installs['DAYS_DIFF']]
installs['ins_f1'] = installs['PAY_DIFF']/installs['AMT_PAYMENT']
installs = installs.set_index('SK_ID_PREV')
installs['SK_ID_PREV'] = installs.index
installs.head()

,SK_ID_CURR,NUM_INSTALMENT_VERSION,NUM_INSTALMENT_NUMBER,DAYS_INSTALMENT,DAYS_ENTRY_PAYMENT,AMT_INSTALMENT,AMT_PAYMENT,PAY_DIFF,DAYS_DIFF,PAY_DIFF2,DAYS_DIFF2,ins_f1,SK_ID_PREV
SK_ID_PREV,,,,,,,,,,,,,
1000001,158271,1.0,1,-268.0,-294.0,6404.310,6404.310,0.0,26.0,1,1,0.0,1000001
1000001,158271,2.0,2,-238.0,-244.0,62039.115,62039.115,0.0,6.0,1,1,0.0,1000001
1000002,101962,1.0,1,-1600.0,-1611.0,6264.000,6264.000,0.0,11.0,1,1,0.0,1000002
1000002,101962,1.0,2,-1570.0,-1575.0,6264.000,6264.000,0.0,5.0,1,1,0.0,1000002
1000002,101962,1.0,3,-1540.0,-1559.0,6264.000,6264.000,0.0,19.0,1,1,0.0,1000002

In [3]:
installs_prev_aggs_dict = {'NUM_INSTALMENT_VERSION':['nunique','count','var'],
                          'DAYS_INSTALMENT':['max','mean',], 
                          'DAYS_ENTRY_PAYMENT':['max','mean'],
                          'AMT_INSTALMENT':['min','max','mean','var','sum','std'], 
                          'AMT_PAYMENT':['min','max','mean','var','sum','std'], 
                          'PAY_DIFF':['min','max','mean','var','sum','std'], 
                          'DAYS_DIFF':['min','max','mean','var','sum','std'], 
                          'PAY_DIFF2':['min','max','mean','var','sum','std'],
                          'DAYS_DIFF2':['min','max','mean','var','sum','std'],
                          'ins_f1':['min','max','mean','var','sum','std']}

installs_prev_aggs = hf.get_aggs_df(installs,'SK_ID_PREV',installs_prev_aggs_dict)
installs_prev_aggs.head()

100.0 %

,NUM_INSTALMENT_VERSION_nunique,NUM_INSTALMENT_VERSION_count,NUM_INSTALMENT_VERSION_var,DAYS_INSTALMENT_max,DAYS_INSTALMENT_mean,DAYS_ENTRY_PAYMENT_max,DAYS_ENTRY_PAYMENT_mean,AMT_INSTALMENT_min,AMT_INSTALMENT_max,AMT_INSTALMENT_mean,...,DAYS_DIFF2_mean,DAYS_DIFF2_var,DAYS_DIFF2_sum,DAYS_DIFF2_std,ins_f1_min,ins_f1_max,ins_f1_mean,ins_f1_var,ins_f1_sum,ins_f1_std
SK_ID_PREV,,,,,,,,,,,,,,,,,,,,,
1000001,2,2,0.500000,-238.0,-253.000000,-244.0,-269.000000,6404.31,62039.115,34221.712500,...,1.000000,0.000000,2,0.00000,0.0,0.000000,0.000000,0.000000e+00,0.000000,0.000000
1000002,2,4,0.250000,-1510.0,-1555.000000,-1554.0,-1574.750000,6264.00,18443.565,9308.891250,...,1.000000,0.000000,4,0.00000,0.0,0.000000,0.000000,0.000000e+00,0.000000,0.000000
1000003,1,3,0.000000,-34.0,-64.000000,-49.0,-79.333333,4951.35,4951.350,4951.350000,...,1.000000,0.000000,3,0.00000,0.0,0.000000,0.000000,0.000000e+00,0.000000,0.000000
1000004,2,7,0.142857,-682.0,-772.000000,-695.0,-798.714286,3391.11,13176.495,4789.022143,...,1.000000,0.000000,7,0.00000,0.0,0.000000,0.000000,0.000000e+00,0.000000,0.000000
1000005,1,11,0.000000,-1418.0,-1543.454545,-1433.0,-1551.909091,14599.26,14713.605,14703.210000,...,0.818182,0.163636,9,0.40452,0.0,5272.693548,479.335794,2.527391e+06,5272.693738,1589.776916

In [5]:
slopes_cols = installs[installs.columns[1:-1]].drop('NUM_INSTALMENT_NUMBER',axis=1).columns
installs_prev_slopes = hf.get_slopes(installs,installs.index.unique(),
                                    'SK_ID_PREV','NUM_INSTALMENT_NUMBER',slopes_cols)
installs_prev_slopes.to_csv('installs_prev_slopes.csv', columns = installs_prev_slopes.columns)

installs_prev_slopes = pd.read_csv('installs_prev_slopes.csv').set_index('SK_ID_PREV')
installs_prev_slopes.head()

99.925 %
0
Found slopes in Index(['NUM_INSTALMENT_VERSION', 'DAYS_INSTALMENT', 'DAYS_ENTRY_PAYMENT',
       'AMT_INSTALMENT', 'AMT_PAYMENT', 'PAY_DIFF', 'DAYS_DIFF', 'PAY_DIFF2',
       'DAYS_DIFF2', 'ins_f1'],
      dtype='object') grouped by SK_ID_PREV with respect to NUM_INSTALMENT_NUMBER

,NUM_INSTALMENT_VERSION_slope,DAYS_INSTALMENT_slope,DAYS_ENTRY_PAYMENT_slope,AMT_INSTALMENT_slope,AMT_PAYMENT_slope,PAY_DIFF_slope,DAYS_DIFF_slope,PAY_DIFF2_slope,DAYS_DIFF2_slope,ins_f1_slope
SK_ID_PREV,,,,,,,,,,
1000001,1.000000,30.0,50.000000,55634.805000,55634.805000,0.000000,-20.000000,0.0,0.000000,0.000000
1000002,0.300000,30.0,18.700000,3653.869500,3653.869500,0.000000,11.300000,0.0,0.000000,0.000000
1000003,0.000000,30.0,29.500000,0.000000,0.000000,0.000000,0.500000,0.0,0.000000,0.000000
1000004,0.107143,30.0,29.785714,1048.434107,1048.434107,0.000000,0.214286,0.0,0.000000,0.000000
1000005,0.000000,30.0,28.655340,-5.106670,-505.083539,499.976869,1.344660,0.0,0.017476,179.169205

In [6]:
installs_prev_weighted = hf.get_weighted(installs,'SK_ID_PREV','NUM_INSTALMENT_VERSION', slopes_cols[3:])
installs_prev_weighted.to_csv('installs_prev_weighted.csv', columns = installs_prev_weighted.columns)
installs_prev_Weighted = pd.read_csv('installs_prev_weighted.csv').set_index('SK_ID_PREV')
installs_prev_weighted.head()

,AMT_INSTALMENT_weighted,AMT_PAYMENT_weighted,PAY_DIFF_weighted,DAYS_DIFF_weighted,PAY_DIFF2_weighted,DAYS_DIFF2_weighted,ins_f1_weighted
SK_ID_PREV,,,,,,,
1000001,40516.634506,40516.634506,0.000000,13.737056,1.0,1.000000,0.000000
1000002,10358.472580,10358.472580,0.000000,23.033469,1.0,1.000000,0.000000
1000003,4951.350000,4951.350000,0.000000,15.473270,1.0,1.000000,0.000000
1000004,5309.912265,5309.912265,0.000000,27.251733,1.0,1.000000,0.000000
1000005,14699.389080,12934.189733,1765.199346,9.717175,1.0,0.850118,632.572757

In [7]:
installs_prev = pd.concat([installs_prev_aggs,installs_prev_slopes,installs_prev_weighted],axis=1)
installs_prev['SK_ID_CURR'] = installs.groupby('SK_ID_PREV').max()['SK_ID_CURR']
installs_prev.head()

,NUM_INSTALMENT_VERSION_nunique,NUM_INSTALMENT_VERSION_count,NUM_INSTALMENT_VERSION_var,DAYS_INSTALMENT_max,DAYS_INSTALMENT_mean,DAYS_ENTRY_PAYMENT_max,DAYS_ENTRY_PAYMENT_mean,AMT_INSTALMENT_min,AMT_INSTALMENT_max,AMT_INSTALMENT_mean,...,DAYS_DIFF2_slope,ins_f1_slope,AMT_INSTALMENT_weighted,AMT_PAYMENT_weighted,PAY_DIFF_weighted,DAYS_DIFF_weighted,PAY_DIFF2_weighted,DAYS_DIFF2_weighted,ins_f1_weighted,SK_ID_CURR
SK_ID_PREV,,,,,,,,,,,,,,,,,,,,,
1000001,2,2,0.500000,-238.0,-253.000000,-244.0,-269.000000,6404.31,62039.115,34221.712500,...,0.000000,0.000000,40516.634506,40516.634506,0.000000,13.737056,1.0,1.000000,0.000000,158271
1000002,2,4,0.250000,-1510.0,-1555.000000,-1554.0,-1574.750000,6264.00,18443.565,9308.891250,...,0.000000,0.000000,10358.472580,10358.472580,0.000000,23.033469,1.0,1.000000,0.000000,101962
1000003,1,3,0.000000,-34.0,-64.000000,-49.0,-79.333333,4951.35,4951.350,4951.350000,...,0.000000,0.000000,4951.350000,4951.350000,0.000000,15.473270,1.0,1.000000,0.000000,252457
1000004,2,7,0.142857,-682.0,-772.000000,-695.0,-798.714286,3391.11,13176.495,4789.022143,...,0.000000,0.000000,5309.912265,5309.912265,0.000000,27.251733,1.0,1.000000,0.000000,260094
1000005,1,11,0.000000,-1418.0,-1543.454545,-1433.0,-1551.909091,14599.26,14713.605,14703.210000,...,0.017476,179.169205,14699.389080,12934.189733,1765.199346,9.717175,1.0,0.850118,632.572757,176456

In [8]:
installs_curr_dict = {}
for i in installs_prev.columns[:-1]:
    installs_curr_dict[i] = ['min','max','mean','sum'US]
installs_curr_aggs = hf.get_aggs_df(installs_prev,'SK_ID_CURR',installs_curr_dict)
installs_curr_aggs.head()

100.0 %

,NUM_INSTALMENT_VERSION_nunique_min,NUM_INSTALMENT_VERSION_nunique_max,NUM_INSTALMENT_VERSION_nunique_mean,NUM_INSTALMENT_VERSION_nunique_sum,NUM_INSTALMENT_VERSION_nunique_median,NUM_INSTALMENT_VERSION_nunique_var,NUM_INSTALMENT_VERSION_nunique_std,NUM_INSTALMENT_VERSION_count_min,NUM_INSTALMENT_VERSION_count_max,NUM_INSTALMENT_VERSION_count_mean,...,DAYS_DIFF2_weighted_median,DAYS_DIFF2_weighted_var,DAYS_DIFF2_weighted_std,ins_f1_weighted_min,ins_f1_weighted_max,ins_f1_weighted_mean,ins_f1_weighted_sum,ins_f1_weighted_median,ins_f1_weighted_var,ins_f1_weighted_std
SK_ID_CURR,,,,,,,,,,,,,,,,,,,,,
100001,1,2,1.500000,3,1.5,0.500000,0.707107,3,4,3.500000,...,0.827156,5.974979e-02,2.444377e-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0
100002,2,2,2.000000,2,2.0,NaN,NaN,19,19,19.000000,...,1.000000,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN
100003,1,2,1.333333,4,1.0,0.333333,0.577350,6,12,8.333333,...,1.000000,6.162976e-33,7.850462e-17,0.0,0.0,0.0,0.0,0.0,0.0,0.0
100004,2,2,2.000000,2,2.0,NaN,NaN,3,3,3.000000,...,1.000000,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN
100005,2,2,2.000000,2,2.0,NaN,NaN,9,9,9.000000,...,0.881375,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN

In [9]:
installs_curr_slopes = hf.get_slopes(installs_prev,installs_prev['SK_ID_CURR'].unique(),
                                     'SK_ID_CURR','DAYS_INSTALMENT_mean',
                                     installs_prev.drop(['DAYS_INSTALMENT_mean'],axis=1).columns[:-1])
installs_curr_slopes.to_csv('installs_curr_slopes.csv', columns = installs_curr_slopes.columns)

installs_curr_slopes = pd.read_csv('installs_curr_slopes.csv').set_index('SK_ID_CURR')
installs_curr_slopes.head()

99.827 %
0
Found slopes in Index(['NUM_INSTALMENT_VERSION_nunique', 'NUM_INSTALMENT_VERSION_count',
       'NUM_INSTALMENT_VERSION_var', 'DAYS_INSTALMENT_max',
       'DAYS_ENTRY_PAYMENT_max', 'DAYS_ENTRY_PAYMENT_mean',
       'AMT_INSTALMENT_min', 'AMT_INSTALMENT_max', 'AMT_INSTALMENT_mean',
       'AMT_INSTALMENT_var', 'AMT_INSTALMENT_sum', 'AMT_INSTALMENT_std',
       'AMT_PAYMENT_min', 'AMT_PAYMENT_max', 'AMT_PAYMENT_mean',
       'AMT_PAYMENT_var', 'AMT_PAYMENT_sum', 'AMT_PAYMENT_std', 'PAY_DIFF_min',
       'PAY_DIFF_max', 'PAY_DIFF_mean', 'PAY_DIFF_var', 'PAY_DIFF_sum',
       'PAY_DIFF_std', 'DAYS_DIFF_min', 'DAYS_DIFF_max', 'DAYS_DIFF_mean',
       'DAYS_DIFF_var', 'DAYS_DIFF_sum', 'DAYS_DIFF_std', 'PAY_DIFF2_min',
       'PAY_DIFF2_max', 'PAY_DIFF2_mean', 'PAY_DIFF2_var', 'PAY_DIFF2_sum',
       'PAY_DIFF2_std', 'DAYS_DIFF2_min', 'DAYS_DIFF2_max', 'DAYS_DIFF2_mean',
       'DAYS_DIFF2_var', 'DAYS_DIFF2_sum', 'DAYS_DIFF2_std', 'ins_f1_min',
       'ins_f1_max', 'ins_f1_mean', 'ins_f1_var', 'ins_f1_sum', 'ins_f1_std',
       'NUM_INSTALMENT_VERSION_slope', 'DAYS_INSTALMENT_slope',
       'DAYS_ENTRY_PAYMENT_slope', 'AMT_INSTALMENT_slope', 'AMT_PAYMENT_slope',
       'PAY_DIFF_slope', 'DAYS_DIFF_slope', 'PAY_DIFF2_slope',
       'DAYS_DIFF2_slope', 'ins_f1_slope', 'AMT_INSTALMENT_weighted',
       'AMT_PAYMENT_weighted', 'PAY_DIFF_weighted', 'DAYS_DIFF_weighted',
       'PAY_DIFF2_weighted', 'DAYS_DIFF2_weighted', 'ins_f1_weighted'],
      dtype='object') grouped by SK_ID_CURR with respect to DAYS_INSTALMENT_mean

,NUM_INSTALMENT_VERSION_nunique_slope,NUM_INSTALMENT_VERSION_count_slope,NUM_INSTALMENT_VERSION_var_slope,DAYS_INSTALMENT_max_slope,DAYS_ENTRY_PAYMENT_max_slope,DAYS_ENTRY_PAYMENT_mean_slope,AMT_INSTALMENT_min_slope,AMT_INSTALMENT_max_slope,AMT_INSTALMENT_mean_slope,AMT_INSTALMENT_var_slope,...,PAY_DIFF2_slope_slope,DAYS_DIFF2_slope_slope,ins_f1_slope_slope,AMT_INSTALMENT_weighted_slope,AMT_PAYMENT_weighted_slope,PAY_DIFF_weighted_slope,DAYS_DIFF_weighted_slope,PAY_DIFF2_weighted_slope,DAYS_DIFF2_weighted_slope,ins_f1_weighted_slope
SK_ID_CURR,,,,,,,,,,,,,,,,,,,,,
158271,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101962,-0.000366,0.036392,-0.000156,1.535310,1.527569,0.995728,-3.904959,-21.895906,-16.483352,-1.038319e+06,...,-0.00000,0.000005,-0.000000,-20.455590,-20.455590,-0.000000,0.003725,-3.739782e-19,0.000056,-0.000000
252457,-0.000355,-0.000000,-0.000118,1.000000,0.994671,0.994553,0.692776,-0.170313,0.405080,-6.989854e+02,...,-0.00000,-0.000000,-0.000000,0.316289,0.316289,-0.000000,0.005497,-0.000000e+00,-0.000000,-0.000000
260094,0.000574,-0.001790,0.000127,0.978155,0.977707,0.994994,5.175619,39.377928,10.355526,7.979208e+05,...,0.00001,-0.000012,0.102166,11.628210,12.398707,-0.770496,0.004451,-9.043727e-06,0.000113,-0.343683
176456,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
installs_curr_slopes.columns

Index(['NUM_INSTALMENT_VERSION_nunique_slope',
       'NUM_INSTALMENT_VERSION_count_slope',
       'NUM_INSTALMENT_VERSION_var_slope', 'DAYS_INSTALMENT_max_slope',
       'DAYS_ENTRY_PAYMENT_max_slope', 'DAYS_ENTRY_PAYMENT_mean_slope',
       'AMT_INSTALMENT_min_slope', 'AMT_INSTALMENT_max_slope',
       'AMT_INSTALMENT_mean_slope', 'AMT_INSTALMENT_var_slope',
       'AMT_INSTALMENT_sum_slope', 'AMT_INSTALMENT_std_slope',
       'AMT_PAYMENT_min_slope', 'AMT_PAYMENT_max_slope',
       'AMT_PAYMENT_mean_slope', 'AMT_PAYMENT_var_slope',
       'AMT_PAYMENT_sum_slope', 'AMT_PAYMENT_std_slope', 'PAY_DIFF_min_slope',
       'PAY_DIFF_max_slope', 'PAY_DIFF_mean_slope', 'PAY_DIFF_var_slope',
       'PAY_DIFF_sum_slope', 'PAY_DIFF_std_slope', 'DAYS_DIFF_min_slope',
       'DAYS_DIFF_max_slope', 'DAYS_DIFF_mean_slope', 'DAYS_DIFF_var_slope',
       'DAYS_DIFF_sum_slope', 'DAYS_DIFF_std_slope', 'PAY_DIFF2_min_slope',
       'PAY_DIFF2_max_slope', 'PAY_DIFF2_mean_slope', 'PAY_DIFF2_var_slope',
       'PAY_DIFF2_sum_slope', 'PAY_DIFF2_std_slope', 'DAYS_DIFF2_min_slope',
       'DAYS_DIFF2_max_slope', 'DAYS_DIFF2_mean_slope', 'DAYS_DIFF2_var_slope',
       'DAYS_DIFF2_sum_slope', 'DAYS_DIFF2_std_slope', 'ins_f1_min_slope',
       'ins_f1_max_slope', 'ins_f1_mean_slope', 'ins_f1_var_slope',
       'ins_f1_sum_slope', 'ins_f1_std_slope',
       'NUM_INSTALMENT_VERSION_slope_slope', 'DAYS_INSTALMENT_slope_slope',
       'DAYS_ENTRY_PAYMENT_slope_slope', 'AMT_INSTALMENT_slope_slope',
       'AMT_PAYMENT_slope_slope', 'PAY_DIFF_slope_slope',
       'DAYS_DIFF_slope_slope', 'PAY_DIFF2_slope_slope',
       'DAYS_DIFF2_slope_slope', 'ins_f1_slope_slope',
       'AMT_INSTALMENT_weighted_slope', 'AMT_PAYMENT_weighted_slope',
       'PAY_DIFF_weighted_slope', 'DAYS_DIFF_weighted_slope',
       'PAY_DIFF2_weighted_slope', 'DAYS_DIFF2_weighted_slope',
       'ins_f1_weighted_slope'],
      dtype='object')

In [14]:
installs_prev.columns

Index(['NUM_INSTALMENT_VERSION_nunique', 'NUM_INSTALMENT_VERSION_count',
       'NUM_INSTALMENT_VERSION_var', 'DAYS_INSTALMENT_max',
       'DAYS_INSTALMENT_mean', 'DAYS_ENTRY_PAYMENT_max',
       'DAYS_ENTRY_PAYMENT_mean', 'AMT_INSTALMENT_min', 'AMT_INSTALMENT_max',
       'AMT_INSTALMENT_mean', 'AMT_INSTALMENT_var', 'AMT_INSTALMENT_sum',
       'AMT_INSTALMENT_std', 'AMT_PAYMENT_min', 'AMT_PAYMENT_max',
       'AMT_PAYMENT_mean', 'AMT_PAYMENT_var', 'AMT_PAYMENT_sum',
       'AMT_PAYMENT_std', 'PAY_DIFF_min', 'PAY_DIFF_max', 'PAY_DIFF_mean',
       'PAY_DIFF_var', 'PAY_DIFF_sum', 'PAY_DIFF_std', 'DAYS_DIFF_min',
       'DAYS_DIFF_max', 'DAYS_DIFF_mean', 'DAYS_DIFF_var', 'DAYS_DIFF_sum',
       'DAYS_DIFF_std', 'PAY_DIFF2_min', 'PAY_DIFF2_max', 'PAY_DIFF2_mean',
       'PAY_DIFF2_var', 'PAY_DIFF2_sum', 'PAY_DIFF2_std', 'DAYS_DIFF2_min',
       'DAYS_DIFF2_max', 'DAYS_DIFF2_mean', 'DAYS_DIFF2_var', 'DAYS_DIFF2_sum',
       'DAYS_DIFF2_std', 'ins_f1_min', 'ins_f1_max', 'ins_f1_mean',
       'ins_f1_var', 'ins_f1_sum', 'ins_f1_std',
       'NUM_INSTALMENT_VERSION_slope', 'DAYS_INSTALMENT_slope',
       'DAYS_ENTRY_PAYMENT_slope', 'AMT_INSTALMENT_slope', 'AMT_PAYMENT_slope',
       'PAY_DIFF_slope', 'DAYS_DIFF_slope', 'PAY_DIFF2_slope',
       'DAYS_DIFF2_slope', 'ins_f1_slope', 'AMT_INSTALMENT_weighted',
       'AMT_PAYMENT_weighted', 'PAY_DIFF_weighted', 'DAYS_DIFF_weighted',
       'PAY_DIFF2_weighted', 'DAYS_DIFF2_weighted', 'ins_f1_weighted',
       'SK_ID_CURR'],
      dtype='object')

In [15]:
installs_curr_weighted = hf.get_weighted(installs_prev,'SK_ID_CURR','DAYS_INSTALMENT_mean',installs_prev.columns[:-1])
installs_curr_weighted.to_csv('installs_curr_weighted.csv',columns = installs_curr_weighted.columns)
installs_curr_weighted = pd.read_csv('installs_curr_weighted.csv').set_index('SK_ID_CURR')
installs_curr_weighted.head()

,NUM_INSTALMENT_VERSION_nunique_weighted,NUM_INSTALMENT_VERSION_count_weighted,NUM_INSTALMENT_VERSION_var_weighted,DAYS_INSTALMENT_max_weighted,DAYS_INSTALMENT_mean_weighted,DAYS_ENTRY_PAYMENT_max_weighted,DAYS_ENTRY_PAYMENT_mean_weighted,AMT_INSTALMENT_min_weighted,AMT_INSTALMENT_max_weighted,AMT_INSTALMENT_mean_weighted,...,PAY_DIFF2_slope_weighted,DAYS_DIFF2_slope_weighted,ins_f1_slope_weighted,AMT_INSTALMENT_weighted_weighted,AMT_PAYMENT_weighted_weighted,PAY_DIFF_weighted_weighted,DAYS_DIFF_weighted_weighted,PAY_DIFF2_weighted_weighted,DAYS_DIFF2_weighted_weighted,ins_f1_weighted_weighted
SK_ID_CURR,,,,,,,,,,,,,,,,,,,,,
100001,0.455312,1.189567,0.022046,-939.431901,-951.768496,-940.225562,-952.112566,1458.868253,2644.991400,1755.529794,...,0.0,1.977023e-17,0.0,1857.685343,1857.685343,0.0,0.292110,0.367128,0.270701,0.0
100002,0.464916,4.416706,0.012235,-5.811455,-68.575172,-11.390452,-73.322213,2150.651045,12342.076863,2687.041878,...,0.0,0.000000e+00,0.0,2871.811755,2871.811755,0.0,4.551368,0.232458,0.232458,0.0
100003,1.331988,10.750209,0.029351,-1547.087353,-1691.442559,-1555.947630,-1699.851117,43061.114400,138213.175173,56749.067860,...,0.0,0.000000e+00,0.0,61800.497050,61800.497050,0.0,8.033257,1.126529,1.126529,0.0
100004,1.226294,1.839442,0.204382,-443.918568,-462.312983,-445.758009,-467.013778,3284.782798,6483.396956,4350.987518,...,0.0,0.000000e+00,0.0,4680.045751,4680.045751,0.0,4.181024,0.613147,0.613147,0.0
100005,0.376200,1.692899,0.020900,-87.654528,-110.226509,-88.406927,-114.657306,905.362175,3321.136952,1173.781595,...,0.0,2.117003e-19,0.0,1273.633828,1273.633828,0.0,4.043873,0.188100,0.165787,0.0

In [18]:
installs_curr = pd.concat([installs_curr_aggs,installs_curr_slopes,installs_curr_weighted],axis=1)
installs_curr = hf.drop_high_corrs(installs_curr,0.95)
installs_curr.columns = ['ins_'+i for i in installs_curr.columns]
installs_curr.to_csv('ins_curr.csv',columns = installs_curr.columns)
installs_curr = pd.read_csv('ins_curr.csv').set_index('SK_ID_CURR')
installs_curr.head()

Removing 266 columns ['NUM_INSTALMENT_VERSION_nunique_std', 'NUM_INSTALMENT_VERSION_count_std', 'NUM_INSTALMENT_VERSION_var_mean', 'NUM_INSTALMENT_VERSION_var_sum', 'NUM_INSTALMENT_VERSION_var_var', 'NUM_INSTALMENT_VERSION_var_std', 'DAYS_INSTALMENT_max_median', 'DAYS_INSTALMENT_max_std', 'DAYS_INSTALMENT_mean_min', 'DAYS_INSTALMENT_mean_mean', 'DAYS_INSTALMENT_mean_sum', 'DAYS_INSTALMENT_mean_median', 'DAYS_INSTALMENT_mean_std', 'DAYS_ENTRY_PAYMENT_max_min', 'DAYS_ENTRY_PAYMENT_max_max', 'DAYS_ENTRY_PAYMENT_max_mean', 'DAYS_ENTRY_PAYMENT_max_sum', 'DAYS_ENTRY_PAYMENT_max_median', 'DAYS_ENTRY_PAYMENT_max_var', 'DAYS_ENTRY_PAYMENT_max_std', 'DAYS_ENTRY_PAYMENT_mean_min', 'DAYS_ENTRY_PAYMENT_mean_max', 'DAYS_ENTRY_PAYMENT_mean_mean', 'DAYS_ENTRY_PAYMENT_mean_sum', 'DAYS_ENTRY_PAYMENT_mean_median', 'DAYS_ENTRY_PAYMENT_mean_var', 'DAYS_ENTRY_PAYMENT_mean_std', 'AMT_INSTALMENT_min_sum', 'AMT_INSTALMENT_min_std', 'AMT_INSTALMENT_max_std', 'AMT_INSTALMENT_mean_var', 'AMT_INSTALMENT_mean_std', 'AMT_INSTALMENT_var_sum', 'AMT_INSTALMENT_var_std', 'AMT_INSTALMENT_sum_std', 'AMT_INSTALMENT_std_var', 'AMT_INSTALMENT_std_std', 'AMT_PAYMENT_min_max', 'AMT_PAYMENT_min_mean', 'AMT_PAYMENT_min_sum', 'AMT_PAYMENT_min_median', 'AMT_PAYMENT_min_var', 'AMT_PAYMENT_min_std', 'AMT_PAYMENT_max_min', 'AMT_PAYMENT_max_max', 'AMT_PAYMENT_max_mean', 'AMT_PAYMENT_max_sum', 'AMT_PAYMENT_max_median', 'AMT_PAYMENT_max_var', 'AMT_PAYMENT_max_std', 'AMT_PAYMENT_mean_min', 'AMT_PAYMENT_mean_max', 'AMT_PAYMENT_mean_mean', 'AMT_PAYMENT_mean_sum', 'AMT_PAYMENT_mean_median', 'AMT_PAYMENT_mean_var', 'AMT_PAYMENT_mean_std', 'AMT_PAYMENT_var_min', 'AMT_PAYMENT_var_max', 'AMT_PAYMENT_var_mean', 'AMT_PAYMENT_var_sum', 'AMT_PAYMENT_var_median', 'AMT_PAYMENT_var_var', 'AMT_PAYMENT_var_std', 'AMT_PAYMENT_sum_min', 'AMT_PAYMENT_sum_max', 'AMT_PAYMENT_sum_mean', 'AMT_PAYMENT_sum_sum', 'AMT_PAYMENT_sum_median', 'AMT_PAYMENT_sum_std', 'AMT_PAYMENT_std_min', 'AMT_PAYMENT_std_max', 'AMT_PAYMENT_std_mean', 'AMT_PAYMENT_std_sum', 'AMT_PAYMENT_std_median', 'AMT_PAYMENT_std_var', 'AMT_PAYMENT_std_std', 'PAY_DIFF_min_sum', 'PAY_DIFF_min_std', 'PAY_DIFF_max_std', 'PAY_DIFF_mean_sum', 'PAY_DIFF_mean_std', 'PAY_DIFF_var_sum', 'PAY_DIFF_var_std', 'PAY_DIFF_std_sum', 'PAY_DIFF_std_var', 'PAY_DIFF_std_std', 'DAYS_DIFF_min_sum', 'DAYS_DIFF_min_std', 'DAYS_DIFF_var_sum', 'DAYS_DIFF_var_std', 'DAYS_DIFF_std_var', 'DAYS_DIFF_std_std', 'PAY_DIFF2_min_std', 'PAY_DIFF2_max_sum', 'PAY_DIFF2_max_var', 'PAY_DIFF2_max_std', 'PAY_DIFF2_mean_sum', 'PAY_DIFF2_mean_std', 'PAY_DIFF2_var_std', 'PAY_DIFF2_sum_min', 'PAY_DIFF2_sum_max', 'PAY_DIFF2_sum_mean', 'PAY_DIFF2_sum_sum', 'PAY_DIFF2_sum_median', 'PAY_DIFF2_sum_var', 'PAY_DIFF2_sum_std', 'PAY_DIFF2_std_min', 'PAY_DIFF2_std_max', 'PAY_DIFF2_std_mean', 'PAY_DIFF2_std_sum', 'PAY_DIFF2_std_median', 'PAY_DIFF2_std_var', 'PAY_DIFF2_std_std', 'DAYS_DIFF2_min_std', 'DAYS_DIFF2_max_sum', 'DAYS_DIFF2_max_var', 'DAYS_DIFF2_max_std', 'DAYS_DIFF2_mean_sum', 'DAYS_DIFF2_sum_min', 'DAYS_DIFF2_sum_max', 'DAYS_DIFF2_sum_mean', 'DAYS_DIFF2_sum_sum', 'DAYS_DIFF2_sum_median', 'DAYS_DIFF2_sum_var', 'DAYS_DIFF2_sum_std', 'DAYS_DIFF2_std_min', 'DAYS_DIFF2_std_max', 'DAYS_DIFF2_std_mean', 'DAYS_DIFF2_std_sum', 'DAYS_DIFF2_std_median', 'DAYS_DIFF2_std_std', 'ins_f1_min_min', 'ins_f1_min_mean', 'ins_f1_min_sum', 'ins_f1_min_var', 'ins_f1_min_std', 'ins_f1_max_sum', 'ins_f1_max_std', 'ins_f1_mean_sum', 'ins_f1_mean_std', 'ins_f1_var_mean', 'ins_f1_var_sum', 'ins_f1_var_median', 'ins_f1_var_var', 'ins_f1_var_std', 'ins_f1_sum_sum', 'ins_f1_sum_std', 'ins_f1_std_sum', 'ins_f1_std_var', 'ins_f1_std_std', 'NUM_INSTALMENT_VERSION_slope_var', 'NUM_INSTALMENT_VERSION_slope_std', 'DAYS_INSTALMENT_slope_sum', 'DAYS_ENTRY_PAYMENT_slope_sum', 'AMT_INSTALMENT_slope_sum', 'AMT_INSTALMENT_slope_std', 'AMT_PAYMENT_slope_max', 'AMT_PAYMENT_slope_mean', 'AMT_PAYMENT_slope_sum', 'AMT_PAYMENT_slope_median', 'AMT_PAYMENT_slope_var', 'AMT_PAYMENT_slope_std', 'PAY_DIFF_slope_sum', 'PAY_DIFF_slope_std', 'DAYS_DIFF_slope_min', 'DAYS_DIFF_slope_sum', 'DAYS_DIFF_slope_var', 'DAYS_DIFF_slope_std', 'AMT_INSTALMENT_weighted_min', 'AMT_INSTALMENT_weighted_max', 'AMT_INSTALMENT_weighted_mean', 'AMT_INSTALMENT_weighted_sum', 'AMT_INSTALMENT_weighted_median', 'AMT_INSTALMENT_weighted_var', 'AMT_INSTALMENT_weighted_std', 'AMT_PAYMENT_weighted_min', 'AMT_PAYMENT_weighted_max', 'AMT_PAYMENT_weighted_mean', 'AMT_PAYMENT_weighted_sum', 'AMT_PAYMENT_weighted_median', 'AMT_PAYMENT_weighted_var', 'AMT_PAYMENT_weighted_std', 'PAY_DIFF_weighted_min', 'PAY_DIFF_weighted_max', 'PAY_DIFF_weighted_mean', 'PAY_DIFF_weighted_sum', 'PAY_DIFF_weighted_median', 'PAY_DIFF_weighted_std', 'DAYS_DIFF_weighted_min', 'DAYS_DIFF_weighted_max', 'DAYS_DIFF_weighted_mean', 'DAYS_DIFF_weighted_sum', 'DAYS_DIFF_weighted_median', 'DAYS_DIFF_weighted_std', 'PAY_DIFF2_weighted_min', 'PAY_DIFF2_weighted_max', 'PAY_DIFF2_weighted_mean', 'PAY_DIFF2_weighted_sum', 'PAY_DIFF2_weighted_median', 'PAY_DIFF2_weighted_var', 'PAY_DIFF2_weighted_std', 'DAYS_DIFF2_weighted_min', 'DAYS_DIFF2_weighted_max', 'DAYS_DIFF2_weighted_mean', 'DAYS_DIFF2_weighted_sum', 'DAYS_DIFF2_weighted_median', 'DAYS_DIFF2_weighted_var', 'DAYS_DIFF2_weighted_std', 'ins_f1_weighted_min', 'ins_f1_weighted_max', 'ins_f1_weighted_mean', 'ins_f1_weighted_sum', 'ins_f1_weighted_median', 'ins_f1_weighted_var', 'ins_f1_weighted_std', 'DAYS_ENTRY_PAYMENT_max_slope', 'AMT_INSTALMENT_sum_slope', 'AMT_PAYMENT_max_slope', 'AMT_PAYMENT_mean_slope', 'AMT_PAYMENT_var_slope', 'AMT_PAYMENT_sum_slope', 'AMT_PAYMENT_std_slope', 'DAYS_DIFF_mean_slope', 'PAY_DIFF2_sum_slope', 'PAY_DIFF2_std_slope', 'DAYS_DIFF2_sum_slope', 'ins_f1_min_slope', 'ins_f1_std_slope', 'DAYS_ENTRY_PAYMENT_slope_slope', 'AMT_PAYMENT_slope_slope', 'AMT_INSTALMENT_weighted_slope', 'AMT_PAYMENT_weighted_slope', 'DAYS_DIFF_weighted_slope', 'PAY_DIFF2_weighted_slope', 'DAYS_DIFF2_weighted_slope', 'ins_f1_weighted_slope', 'NUM_INSTALMENT_VERSION_var_weighted', 'DAYS_INSTALMENT_mean_weighted', 'DAYS_ENTRY_PAYMENT_max_weighted', 'DAYS_ENTRY_PAYMENT_mean_weighted', 'AMT_PAYMENT_min_weighted', 'AMT_PAYMENT_max_weighted', 'AMT_PAYMENT_mean_weighted', 'AMT_PAYMENT_var_weighted', 'AMT_PAYMENT_sum_weighted', 'AMT_PAYMENT_std_weighted', 'PAY_DIFF2_max_weighted', 'PAY_DIFF2_mean_weighted', 'PAY_DIFF2_sum_weighted', 'PAY_DIFF2_std_weighted', 'DAYS_DIFF2_max_weighted', 'DAYS_DIFF2_mean_weighted', 'DAYS_DIFF2_sum_weighted', 'DAYS_DIFF2_std_weighted', 'ins_f1_min_weighted', 'DAYS_INSTALMENT_slope_weighted', 'DAYS_ENTRY_PAYMENT_slope_weighted', 'AMT_PAYMENT_slope_weighted', 'AMT_INSTALMENT_weighted_weighted', 'AMT_PAYMENT_weighted_weighted', 'PAY_DIFF_weighted_weighted', 'DAYS_DIFF_weighted_weighted', 'PAY_DIFF2_weighted_weighted', 'DAYS_DIFF2_weighted_weighted', 'ins_f1_weighted_weighted']

,NUM_INSTALMENT_VERSION_nunique_min,NUM_INSTALMENT_VERSION_nunique_max,NUM_INSTALMENT_VERSION_nunique_mean,NUM_INSTALMENT_VERSION_nunique_sum,NUM_INSTALMENT_VERSION_nunique_median,NUM_INSTALMENT_VERSION_nunique_var,NUM_INSTALMENT_VERSION_count_min,NUM_INSTALMENT_VERSION_count_max,NUM_INSTALMENT_VERSION_count_mean,NUM_INSTALMENT_VERSION_count_sum,...,ins_f1_var_weighted,ins_f1_sum_weighted,ins_f1_std_weighted,NUM_INSTALMENT_VERSION_slope_weighted,AMT_INSTALMENT_slope_weighted,PAY_DIFF_slope_weighted,DAYS_DIFF_slope_weighted,PAY_DIFF2_slope_weighted,DAYS_DIFF2_slope_weighted,ins_f1_slope_weighted
SK_ID_CURR,,,,,,,,,,,,,,,,,,,,,
100001,1,2,1.500000,3,1.5,0.500000,3,4,3.500000,7,...,0.0,0.0,0.0,0.026455,355.585895,0.0,-0.141095,0.0,1.977023e-17,0.0
100002,2,2,2.000000,2,2.0,NaN,19,19,19.000000,19,...,0.0,0.0,0.0,0.003670,160.917250,0.0,-0.132134,0.0,0.000000e+00,0.0
100003,1,2,1.333333,4,1.0,0.333333,6,12,8.333333,25,...,0.0,0.0,0.0,0.022013,10166.850507,0.0,-0.126621,0.0,0.000000e+00,0.0
100004,2,2,2.000000,2,2.0,NaN,3,3,3.000000,3,...,0.0,0.0,0.0,0.306574,1599.307079,0.0,-2.452589,0.0,0.000000e+00,0.0
100005,2,2,2.000000,2,2.0,NaN,9,9,9.000000,9,...,0.0,0.0,0.0,0.012540,161.051652,0.0,-0.529815,0.0,2.117003e-19,0.0